name: "[CI] Lint"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  lint-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - run: npm ci
        name: Install JS deps

      - run: npm run lint
        name: Lint JS files

      - run: npm run stylelint
        name: Lint SCSS files

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec erb_lint app/**/*.erb
        name: Lint ERB files
